# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Linux
  pool: 
    vmImage:'ubuntu-latest'
  steps:
  - script: echo 'hello'

name: 'Test CI'
trigger:
  batch: true

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: echo '$(Build.BuildNumber)' ## output run number
