---
jobs:
  - job: Build_And_Test
    displayName: Run TOX
    steps:
      - task: Bash@3
        name: bump
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script:
            git config --global user.email "davidmarkellis@yahoo.com" &&
            git config --global user.name "David Ellis" &&
            pip install bumpversion && 
            bumpversion --allow-dirty --commit --tag --config-file=$(Build.Repository.LocalPath)/.bumpversion.toml  --list patch
            git push
      - task: Bash@3
        name: dependencies
        inputs:
          targetType: 'inline'
          script: pip install tox pytest-azurepipelines
      - task: Bash@3
        name: tox
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script: tox
