# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# steps:
jobs:
- job: build_artifact
  pool: BLD-WEU-01
    displayName: 'Bump Version, Build, Test the Artifact amd Publish'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: pip install tox pytest-azurepipelines
              tox
