---
jobs:
  - job: Display_Version
    displayName: Run TOX
    steps:
      - task: Bash@3
        name: dependencies
        inputs:
          targetType: 'inline'
          script: pip install tox pytest-azurepipelines
      - task: Bash@3
        name: tox
        inputs:
          targetType: 'inline'
          script: tox
