---
jobs:
  - job: Build_And_Test
    displayName: Run TOX
    steps:
      - task: Bash@3
        name: bump
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script:
            git config --global user.email "david.ellis@iongroup.com" &&
            git config --global user.name "davidmellis" &&
            git config --global user.password "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" &&
            pip install bumpversion && 
            bumpversion --allow-dirty --commit --tag --config-file=$(Build.Repository.LocalPath)/.bumpversion.toml  --list patch &&
            git push origin HEAD:main
      - task: Bash@3
        name: dependencies
        inputs:
          targetType: 'inline'
          script: pip install tox pytest-azurepipelines
      - task: Bash@3
        name: tox
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script: tox
