---
jobs:
  - job: Build_And_Test
    displayName: 'Bump, Push and TOX'
    steps:
      - task: InstallSSHKey@0
        displayName: "Install an SSH key"
        inputs:
          knownHostsEntry: 'SHA256:buDzZTkt42dcFjoSuKz3Hau8xzjdcC7YSBN5viSeU+c david.ellis@iongroup.com'
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC19tGzVZAYRphXl90lV5/IY4bRTOpOSV04Zx5hFhTFCctR2aTV8Zzx1gtFiCDdD79Ef62AfH4J0E1eD2+J7Lwap80EdDo29tNorkZWoG4MqFhrBW6ImF+fQLmOI6orneIBL+oFZaeBN17kr1OCRfSmAUZh3B1Cl5xJH+IcJhb7u20K4ZQcSKm5jQ/UYUtxcu5OGcUSxIeD/PQcYkp+8TpUbBYPy27+r9jLaJy2XQYVxUeM/MuagRTSR+qPMvhaoyjgkh18qGnc3VwVyxhpOo3yM+SmNZflcDf1SOoNEcDGcURuBw3hbisqsVKLOaqz/BQfq3YufoKY9RhQ7dvuxeCWqcYomums567WAXDwn/573Bd18Qtry9OadWxBBmQf6G7WqJ7IqhaHbqjqGA+LkX+h6Y1HWVzB+Pi3LIIxXv+IU1GWs88Q7no70M1mH6GysDDSwbmAG932myZZIFicycbUiDw2sL8cCbQQAhLej4FC194DXxPeeUGsVrwH/X5KHgs= david.ellis@iongroup.com'
          sshKeySecureFile: 'id_rsa'
          sshPassphrase: 'yieks7dry'
      - task: ShellScript@2
        displayName: 'Bump version and Push Repo with no-ci - to stop it looping builds'
        name: push_new_version
        inputs:
          targetType: 'filePath'
          scriptPath: "$(Build.Repository.LocalPath)/push.sh"
          args: "$(Build.Repository.LocalPath) $(Build.BuildId)"
      - task: Bash@3
        name: dependencies
        inputs:
          targetType: 'inline'
          script: pip install tox pytest-azurepipelines
      - task: Bash@3
        name: tox
        displayName: 'Run TOX to test and build artifact'
        inputs:
          targetType: 'inline'  
          workingDirectory: $(Build.Repository.LocalPath)
          script: tox
