---
jobs:
  - job: Display_Version
    displayName: Run TOX
    steps:
      - task: Bash@3
        name: dependencies
        inputs:
          targetType: 'inline'
          script: pip install tox pytest-azurepipelines
      - task: Bash@3
        name: tox
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script: tox
      - task: Bash@3
        name: bump
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script: 
              pip install bumpversion
              bumpversion --allow-dirty --config-file=$(Build.Repository.LocalPath)/.bumpversion.toml  --list patch
