# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: SetVersionNumber
  steps:
  - script: echo '$(Build.BuildNumber)'
  - script: sed -i 's/$VERSION/$(Build.BuildId)/g' setup.cfg
  - script: cat setup.cfg
  
- task: PublishBuildArtifacts@1
  name: publish_wheel
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist/'
    ArtifactName: 'testci'
    publishLocation: 'Container'     