---
jobs:
  - job: Build_And_Test
    displayName: 'Write New Version, Test, Build and Publish Artifact'
    steps:
      - task: InstallSSHKey@0
        name: private_key
        displayName: "Install an SSH key"
        inputs:
          knownHostsEntry: 'SHA256:buDzZTkt42dcFjoSuKz3Hau8xzjdcC7YSBN5viSeU+c david.ellis@iongroup.com'
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC19tGzVZAYRphXl90lV5/IY4bRTOpOSV04Zx5hFhTFCctR2aTV8Zzx1gtFiCDdD79Ef62AfH4J0E1eD2+J7Lwap80EdDo29tNorkZWoG4MqFhrBW6ImF+fQLmOI6orneIBL+oFZaeBN17kr1OCRfSmAUZh3B1Cl5xJH+IcJhb7u20K4ZQcSKm5jQ/UYUtxcu5OGcUSxIeD/PQcYkp+8TpUbBYPy27+r9jLaJy2XQYVxUeM/MuagRTSR+qPMvhaoyjgkh18qGnc3VwVyxhpOo3yM+SmNZflcDf1SOoNEcDGcURuBw3hbisqsVKLOaqz/BQfq3YufoKY9RhQ7dvuxeCWqcYomums567WAXDwn/573Bd18Qtry9OadWxBBmQf6G7WqJ7IqhaHbqjqGA+LkX+h6Y1HWVzB+Pi3LIIxXv+IU1GWs88Q7no70M1mH6GysDDSwbmAG932myZZIFicycbUiDw2sL8cCbQQAhLej4FC194DXxPeeUGsVrwH/X5KHgs= david.ellis@iongroup.com'
          sshKeySecureFile: 'ssh_private'
          sshPassphrase: $(passphrase)
      - task: Bash@3
        name: build_one
        inputs:
          targetType: 'inline'
<<<<<<< HEAD
          script: export BUILD_ID=$(Build.BuildId) 
      - task: Bash@3
        inputs:
=======
          script: 
            bash ./bin/build_one.sh
      - task: Bash@3
        name: build_two
        inputs:
          targetType: 'inline'
          script: 
            bash ./bin/build_two.sh
 
      - task: Bash@3
        name: build_three
        inputs:
          targetType: 'inline'
          script: 
            bash ./bin/build_three.sh
 
