# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
jobs:
  - job: Display_Version
    displayName: Run TOX 
    steps:
     - task: Bash@3
        inputs:
          targetType: 'inline'
          script: pip install tox pytest-azurepipelines
     - task: Bash@3
        inputs:
          targetType: 'inline'
          script: git status
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: tox
