---
jobs:
  - job: Build_And_Test
    displayName: Run TOX
    steps:
      - task: Bash@3
        name: bump
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script:
            #            git config --global user.email "david.ellis@iongroup.com" &&
            #git config --global user.name "davidmellis" &&
            #git config --global user.password $(secrets.GH_TOKEN) &&
            #git config --list --show-origin &&
            #pip install bumpversion && 
            bumpversion --allow-dirty --commit --tag --config-file=$(Build.Repository.LocalPath)/.bumpversion.toml  --list patch
#            git push origin HEAD:main
      - task: InstallSSHKey@0
        displayName: 'Install an SSH key'
        inputs:
          knownHostsEntry: 'SHA256:1|Lc8b91Rj9dFe77WVZwhzZvuyCh8=|pcSYO5bHGgNBi9AeoO+e+mpTs7M= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
|1|Nja9M8yfO1aeWhzquX1tGe+ad0I=|crYoQdCbMhLoY/GG7Mj1szKLl1A= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
|1|cpM5upHpaaAGygU3wIjYeLcHfaU=|Y4LE0bBddWaDuEWGyfAvPpfc0eI= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= david.ellis@iongroup.com' 
          sshPublicKey: 'id_rsa.pub'
          sshKeySecureFile: 'id_rsa'
          sshPassphrase: 'yieks7dry'
      - task: ShellScript@2
        name: push_new_version
        inputs:
          scriptPath: 'push.sh'
      - task: Bash@3
        name: dependencies
        inputs:
          targetType: 'inline'
          script: pip install tox pytest-azurepipelines
      - task: Bash@3
        name: tox
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script: tox

