# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# steps:
# - task: PublishBuildArtifacts@1
#   name: publish_bling
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/dist/'
#     ArtifactName: 'testci'
#     publishLocation: 'Container'     
jobs:
- job: create_aad_token
  pool: BLD-WEU-01
  displayName: Create AAD token
  steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Vsts-Dealogic-DataScience-PIE'
        KeyVaultName: 'databricks-iona-lib'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: PowerShell@2
      name: generateToken
      inputs:
        targetType: inline
        script: |
            $body = @{
              client_id="$(databricks-iona-lib-key)"
              grant_type="client_credentials"
              scope="2ff814a6-3304-4ab8-85cb-cd0e6f879c1d/.default"
              client_secret="$(databricks-iona-lib-secret)"
            }
            $response = Invoke-WebRequest -Uri "https://login.microsoftonline.com/f685370c-0ace-4adf-8ba8-409a97536827/oauth2/v2.0/token" -Method Post -Body $body -ContentType application/x-www-form-urlencoded
            $token = ($response.Content | ConvertFrom-Json).access_token
            write-host "##vso[task.setvariable variable=aad_token;isoutput=true]$token"
        pwsh: true

        # - task: DownloadBuildArtifacts@0
        #   displayName: 'Download Build Artifacts'
        #   inputs:
        #     artifactName: iona-databricks
        #     downloadPath: $(System.DefaultWorkingDirectory)

# jobs:
# - job: SetVersionNumber
#   steps:
#   - script: echo '$(Build.BuildNumber)'
#   - script: sed -i 's/$VERSION/$(Build.BuildId)/g' setup.cfg
#   - script: cat setup.cfg
  
